services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: dev
        environment:
            SERVER_NAME: :80
        ports:
            - 80:80
        volumes:
            - ./:/app
            - caddy_data:/data
            - caddy_config:/config