name: Build and Push Docker Image

on:
    release:
        types: [published]

jobs:
    build-and-push:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Check Out Repository
              uses: actions/checkout@v2

            - name: Log in to GitHub Container Registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Build Docker image
              run: |
                  REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
                  TAG=$(echo ${{ github.ref_name }} | tr '/' '-') # Replace / with -
                  docker build . -t ghcr.io/$REPO_LOWER/vps_example:$TAG -t ghcr.io/$REPO_LOWER/vps_example:latest

            - name: Push Docker image to GitHub Packages
              run: |
                  REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')
                  TAG=$(echo ${{ github.ref_name }} | tr '/' '-') # Replace / with -
                  docker push ghcr.io/$REPO_LOWER/vps_example:$TAG
                  docker push ghcr.io/$REPO_LOWER/vps_example:latest
